import { NextResponse } from "next/server";

export function GET() {
    return NextResponse.json([
        {"name":"Vesktop Mica","description":"A basic transparency import to make Acrylic/Mica/Tabbed effects visible","import":"@import url(//dablulite.github.io/css-snippets/VesktopMica/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/256241802-b8f645d8-3a9d-44d9-b3a4-5292e1a9998d.png"},
        {"name":"Accent Swap","description":"A snippet that makes it simple to swap the Accent/Brand color of Discord","import":"@import url(//dablulite.github.io/css-snippets/AccentSwap/import.css);\\n:root:root {\\n    --accent-h: 235;\\n    --accent-s: 86%;\\n    --accent-l: 65%;\\n};","screenshot":"https://user-images.githubusercontent.com/73998678/265542313-ebc24e8f-70b6-4d77-bb84-c8584b60e4b7.png"},
        {"name":"Account Details Grid","description":"A refresh to the now archived \"account details columns\" snippet","import":"@import url(//dablulite.github.io/css-snippets/AccountDetailsGrid/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/239905591-d8f638d5-30f4-4dbd-b171-b2a146ce282e.png"},
        {"name":"Better \"Authorized Apps\" Tab","description":"A redesign to the Authorized app cards, as well as a counter at the top of the tab","import":"@import url(//dablulite.github.io/css-snippets/BetterAuthApps/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/253537521-d403610f-70b2-46f1-a974-d712a5597d2c.png"},
        {"name":"Better Floating Editor for BetterDiscord","description":"Redesign of BetterDiscord\'s floating editor, with unlocked max width and height","import":"@import url(//dablulite.github.io/css-snippets/BetterFloatingEditor/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/239349133-dab400e5-c2bf-423d-b6f4-3984c4eb1027.png"},
        {"name":"Better Modals","description":"A redesign to the classic Discord modals, giving them a new breath of life","import":"@import url(//dablulite.github.io/css-snippets/BetterModals/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/255169454-a78462b5-f9b7-402e-9875-c90203d09689.png"},
        {"name":"Better Nitro Profile Borders","description":"Gets rid of the unsightly outer 4px border/padding and replaces it with a gradient border around the user info area, like in Discord RN","import":"@import url(\"https://dablulite.github.io/css-snippets/BetterNitroProfileBorder/import.css\");","screenshot":"https://user-images.githubusercontent.com/73998678/273147156-dcf49d77-8b2f-4ef4-bc01-13cd8c3af3ba.png"},
        {"name":"Better Status Picker","description":"A redesign to the simple status picker that gives each button an accent that matches the status, as well as condensing the UI","import":"@import url(\"https://dablulite.github.io/css-snippets/BetterStatusPicker/import.css\");","screenshot":"https://user-images.githubusercontent.com/73998678/271073478-a54f624e-3a50-4a8a-af8e-0fc71b64aa32.png"},
        {"name":"Better Windows Titlebar","description":"A redesign to the original Windows titlebar, making it bigger, as well as giving it the functionality of displaying custom tags, eg: for Colorways","import":"@import url(//dablulite.github.io/css-snippets/BetterTitlebar/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/253539203-e5fe7d6f-0884-4f62-924c-99c40ab82505.png"},
        {"name":"Consistent Chatbar","description":"A snippet that artificially makes the chatbar look like a continuous user area","import":"@import url(//dablulite.github.io/css-snippets/ConsistentChatbar/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/255886838-055558c4-b618-441d-afc1-7dd73a804495.png"},
        {"name":"Declutter Bar","description":"A modified version of the \"Better Titlebar\" snippet, that moves the channel actions (the bar above the chat) inside the titlebar","import":"@import url(//dablulite.github.io/css-snippets/DeclutterBar/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/268488397-4c1a6fb0-803d-451d-9cf6-df1fbe84122c.png"},
        {"name":"Disable Picture-in-picture","description":"Allows you to hide the Pictire-in-picture (Not-detached) window without stopping playback in activities like YouTube","import":"@import url(//dablulite.github.io/css-snippets/DisablePIP/import.css);"},
        {"name":"Discord Teal Brand","description":"Changes all \"brand-hsl\" values for \"teal-hsl\"","import":"@import url(//dablulite.github.io/css-snippets/DiscordTeal/import.css);"},
        {"name":"Free Nitro Profile","description":"A replica of the nitro profile customization system","import":"@import url(//dablulite.github.io/css-snippets/FreeNitroProfile/import.css);"},
        {"name":"DaBluLite\'s Horizontal Server List","description":"A different impementation of Gibbu\'s original HSL snippet","import":"@import url(//dablulite.github.io/css-snippets/HorizontalServerList/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/259088912-7e79e017-babd-4c08-877e-12a6cabe4701.png"},
        {"name":"Immersive Mode","description":"A snippet combining the minimalistic approach of DeclutterBar\'s titlebar, and the lack thereof","import":"@import url(\"https://dablulite.github.io/css-snippets/ImmersiveMode/import.css\");","screenshot":"https://user-images.githubusercontent.com/73998678/281175690-fc813dbf-bb1f-4f8f-b74a-4c66b11bdd80.png"},
        {"name":"macOS Titlebar","description":"A replica of the macOS traffic lights","import":"@import url(//dablulite.github.io/css-snippets/MacosTitlebar/import.css);\\n:root {\\n    --mactitlebar-left-margin: 5px;\\n    --mactitlebar-top-margin: 10px;\\n    --mactitlebar-button-width: 20px;\\n    --mactitlebar-button-height: 20px;\\n    --mactitlebar-button-border-radius: 50px;\\n    --mactitlebar-close-btn-back: #f25056;\\n    --mactitlebar-min-btn-back: #fac536;\\n    --mactitlebar-max-btn-back: #39ea49;\\n    --macbuttons-serverlist-inner-top-margin: 32px;\\n}"},
        {"name":"Hotfix for the Nitro Themes","description":"Hotfix that styles the previously unstyled areas when using Nitro Themes","import":"@import url(//dablulite.github.io/css-snippets/NitroThemesFix/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/239354681-a60edaf6-2a1a-46f6-b0d8-e31a76dbc484.png"},
        {"name":"Nitro-like Profiles","description":"A redesign on the classic profile popups inspired by the nitro profiles","import":"@import url(//dablulite.github.io/css-snippets/NitrolikeProfiles/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/239355260-486a77c2-d0a8-4f5a-a528-062f551c593f.png"},
        {"name":"Omnibar","description":"A combined Guild bar and User area","import":"@import url(//dablulite.github.io/css-snippets/Omnibar/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/261933550-5f49f6f1-b328-4896-99ca-a93ed06f65fb.png"},
        {"name":"Pretty Folder Icons","description":"Makes the expanded folder icons white and their backgrounds colored","import":"@import url(//dablulite.github.io/css-snippets/PrettyFolderIcons/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/269743768-53d0defb-0245-49cb-a517-b610ef7f5261.png"},
        {"name":"Servers List","description":"A fully working server list with labels","import":"@import url(//dablulite.github.io/css-snippets/ServersList/import.css);\\n:root {\\n  --guild-list-width: 290px;\\n  --guild-list-height: 48px;\\n  --guild-item-radius: 50px;\\n  --guild-item-spacing: 8px;\\n  --guild-item-font-size: 16px;\\n}","screenshot":"https://user-images.githubusercontent.com/73998678/258642242-c61e6921-c20b-40cf-a5aa-fb42833f30e4.png"},
        {"name":"Spotify Activity (& Controls for Vencord) Redesign","description":"A simple redesign for the Spotify activity portions in user popouts and Vencord\'s Spotify Controls to match the actual Spotify UI","import":"@import url(\"https://dablulite.github.io/css-snippets/SpotifyActivityRedesign/import.css\");","screenshot":"https://user-images.githubusercontent.com/73998678/271072533-21b9a770-3c42-47cd-8d58-1caa66a91341.png"},
        {"name":"Super User Area","description":"Yet another User area redesign, this time aiming to unify Discord\'s main actions (Home, Account, Settings, etc...)","import":"@import url(//dablulite.github.io/css-snippets/SuperUserArea/import.css);","screenshot":"https://user-images.githubusercontent.com/73998678/269060528-d8011e75-6d2c-4f00-b81b-0585c31228cf.png"}
    ])
}